/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: d70564e573467b0001913faa6501b6bfbbf066a2 */

#if PHP_VERSION_ID >= 80000
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(arginfo_filemagic, 0, 1, MAY_BE_STRING|MAY_BE_FALSE)
	ZEND_ARG_TYPE_INFO(0, path, IS_STRING, 0)
	ZEND_ARG_TYPE_MASK(0, flag, MAY_BE_LONG|MAY_BE_STRING, "MAGIC_NONE or MAGIC_FILE")
	ZEND_ARG_TYPE_MASK(0, magic_path, MAY_BE_STRING|MAY_BE_LONG, "MAGIC_FILE or MAGIC_NONE")
ZEND_END_ARG_INFO()
#else
ZEND_BEGIN_ARG_INFO_EX(arginfo_filemagic, 0, 0, 1)
	ZEND_ARG_INFO(0, path)
	ZEND_ARG_INFO(0, flag)
	ZEND_ARG_INFO(0, magic)
ZEND_END_ARG_INFO()
#endif
